services:
  nginx:
    container_name: frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - energet-network

networks:
  energet-network:
    external: true
    name: energet-network
