version: "3.9"
services:
  nginx-frontend:
    container_name: frontendapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8011:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/ssl:ro
    environment:
      NODE_ENV: production
