services:
  nginx-frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    networks:
      - energet-network

networks:
  energet-network:
    external: true
    name: energet-network
